# Generated by Django 5.2.6 on 2025-10-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('setor', models.CharField(blank=True, max_length=25, null=True)),
                ('assunto', models.CharField(max_length=200)),
                ('conteudo_extraido', models.TextField(blank=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('data_publicacao', models.DateField(auto_now_add=True, null=True)),
                ('prazo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
