# Generated by Django 5.2.6 on 2025-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='prazo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
